### ISSUE TITLE
Transmogrification Sets interfere with previous manual transmogrification

### ISSUE THREAD

**Issue by Trinitarius** [azerothcore/mod-transmog#85]
Server: ChromieCraft
Client: EN

Transmogrification resets to the original item appearance after re-logging when previously applying a set appearance on items that have been manually transmogrified before with the same or a different appearance. This can be avoided by first removing every previous transmogrification manually and then applying the set.

**Comment by anhility** [comment]
I've had the same bug regarding tmog sets and have a theory why some items revert to their normal appearances.
Say you have two gear sets for you specs (outfitter or the ingame manager, whatever) but the two sets share some items between them.
When applying the set appearance to the first gear set so does it seem to give a tag to the items for what appearance they should show instead.
But as you apply the tmog set appearance to your second gear set it seems like the items shared between the sets get double tagged and cause the bug.

For example, let's say the pants are shared for both gear sets but not your chest.
Both the pants and the chest piece get the appearance tag from applying the tmog set.
But when you swap gear, your pants get a second tag of the same set appearance but now your second chest piece get its first tag.
Then (my guess) is when the game is drawing your character (login/change zone/whatever) it looks for what appearance your items should have, but since you still have the same pants equipped something in the script bugs out as you no longer have the chest equipped that corresponds to the pants first appearance tag, so it defaults it back to it's original model.
